BEGIN TRANSACTION;

DROP TABLE player CASCADE;
DROP TABLE game CASCADE;
DROP TABLE participates CASCADE;
DROP TABLE course CASCADE;
DROP TABLE hole CASCADE;
DROP TABLE result CASCADE;
DROP TYPE "gameState";

COMMIT;
